---
- name: Initialize Kubernetes master node
  hosts: master
  become: yes
  vars:
    master_ip: "192.168.57.10"
    pod_cidr: "10.244.0.0/16"
  tasks:
    - name: Check if cluster is already initialized
      stat:
        path: /etc/kubernetes/admin.conf
      register: kubeadm_init

    - name: Initialize Kubernetes cluster
      command: >
        kubeadm init
        --apiserver-advertise-address={{ master_ip }}
        --pod-network-cidr={{ pod_cidr }}
        --node-name master
      when: not kubeadm_init.stat.exists

    - name: Create .kube directory for vagrant user
      file:
        path: /home/vagrant/.kube
        state: directory
        owner: vagrant
        group: vagrant
        mode: '0755'

    - name: Copy kubeconfig for vagrant user
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/vagrant/.kube/config
        owner: vagrant
        group: vagrant
        mode: '0644'
        remote_src: yes

    - name: Create .kube directory for root
      file:
        path: /root/.kube
        state: directory
        mode: '0755'

    - name: Copy kubeconfig for root
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /root/.kube/config
        mode: '0644'
        remote_src: yes

    - name: Install Flannel CNI
      become_user: vagrant
      command: kubectl apply -f https://github.com/flannel-io/flannel/releases/latest/download/kube-flannel.yml
      environment:
        KUBECONFIG: /home/vagrant/.kube/config
      register: flannel_install
      until: flannel_install.rc == 0
      retries: 3
      delay: 10

    - name: Wait for Flannel DaemonSet to be created
      become_user: vagrant
      shell: kubectl get daemonset -n kube-flannel kube-flannel-ds 2>/dev/null
      environment:
        KUBECONFIG: /home/vagrant/.kube/config
      register: flannel_ds
      until: flannel_ds.rc == 0
      retries: 10
      delay: 5
      ignore_errors: yes

    - name: Generate join command
      command: kubeadm token create --print-join-command
      register: join_command_raw

    - name: Set join command as fact
      set_fact:
        join_command: "{{ join_command_raw.stdout_lines[0] }}"

    - name: Display join command
      debug:
        msg: "Join command: {{ join_command }}"
